/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.ui.contentassist;

import org.xtext.slr.ui.contentassist.AbstractReliSRSProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ReliSRSProposalProvider extends AbstractReliSRSProposalProvider {
}
