/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Classification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.slr.reliSRS.Classification#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Classification#getResponse <em>Response</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Classification#getResultat <em>Resultat</em>}</li>
 * </ul>
 *
 * @see org.xtext.slr.reliSRS.ReliSRSPackage#getClassification()
 * @model
 * @generated
 */
public interface Classification extends EObject
{
  /**
   * Returns the value of the '<em><b>Question</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getClassification_Question()
   * @model unique="false"
   * @generated
   */
  EList<String> getQuestion();

  /**
   * Returns the value of the '<em><b>Response</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getClassification_Response()
   * @model unique="false"
   * @generated
   */
  EList<String> getResponse();

  /**
   * Returns the value of the '<em><b>Resultat</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resultat</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getClassification_Resultat()
   * @model unique="false"
   * @generated
   */
  EList<String> getResultat();

} // Classification
