/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Conflict Resolution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.slr.reliSRS.ConflictResolution#getCDecision <em>CDecision</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.ConflictResolution#getCNombre <em>CNombre</em>}</li>
 * </ul>
 *
 * @see org.xtext.slr.reliSRS.ReliSRSPackage#getConflictResolution()
 * @model
 * @generated
 */
public interface ConflictResolution extends EObject
{
  /**
   * Returns the value of the '<em><b>CDecision</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.slr.reliSRS.CDecision}.
   * The literals are from the enumeration {@link org.xtext.slr.reliSRS.CDecision}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CDecision</em>' attribute list.
   * @see org.xtext.slr.reliSRS.CDecision
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getConflictResolution_CDecision()
   * @model unique="false"
   * @generated
   */
  EList<CDecision> getCDecision();

  /**
   * Returns the value of the '<em><b>CNombre</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>CNombre</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getConflictResolution_CNombre()
   * @model unique="false"
   * @generated
   */
  EList<String> getCNombre();

} // ConflictResolution
