/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.slr.reliSRS.Model#getProjectName <em>Project Name</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Model#getParticipants <em>Participants</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Model#getPhase <em>Phase</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Model#getClassification <em>Classification</em>}</li>
 * </ul>
 *
 * @see org.xtext.slr.reliSRS.ReliSRSPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Project Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Project Name</em>' attribute.
   * @see #setProjectName(String)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getModel_ProjectName()
   * @model
   * @generated
   */
  String getProjectName();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Model#getProjectName <em>Project Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Project Name</em>' attribute.
   * @see #getProjectName()
   * @generated
   */
  void setProjectName(String value);

  /**
   * Returns the value of the '<em><b>Participants</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Participants</em>' containment reference.
   * @see #setParticipants(Participants)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getModel_Participants()
   * @model containment="true"
   * @generated
   */
  Participants getParticipants();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Model#getParticipants <em>Participants</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Participants</em>' containment reference.
   * @see #getParticipants()
   * @generated
   */
  void setParticipants(Participants value);

  /**
   * Returns the value of the '<em><b>Phase</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.slr.reliSRS.Phases}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phase</em>' containment reference list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getModel_Phase()
   * @model containment="true"
   * @generated
   */
  EList<Phases> getPhase();

  /**
   * Returns the value of the '<em><b>Classification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classification</em>' containment reference.
   * @see #setClassification(Classification)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getModel_Classification()
   * @model containment="true"
   * @generated
   */
  Classification getClassification();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Model#getClassification <em>Classification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Classification</em>' containment reference.
   * @see #getClassification()
   * @generated
   */
  void setClassification(Classification value);

} // Model
