/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Phases</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.slr.reliSRS.Phases#getPhaseName <em>Phase Name</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Phases#getDecisionPerUser <em>Decision Per User</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Phases#getStatisticsOnExclusionCriteria <em>Statistics On Exclusion Criteria</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Phases#getConflictResolution <em>Conflict Resolution</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.Phases#getResult <em>Result</em>}</li>
 * </ul>
 *
 * @see org.xtext.slr.reliSRS.ReliSRSPackage#getPhases()
 * @model
 * @generated
 */
public interface Phases extends EObject
{
  /**
   * Returns the value of the '<em><b>Phase Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Phase Name</em>' attribute.
   * @see #setPhaseName(String)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getPhases_PhaseName()
   * @model
   * @generated
   */
  String getPhaseName();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Phases#getPhaseName <em>Phase Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Phase Name</em>' attribute.
   * @see #getPhaseName()
   * @generated
   */
  void setPhaseName(String value);

  /**
   * Returns the value of the '<em><b>Decision Per User</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision Per User</em>' containment reference.
   * @see #setDecisionPerUser(DecisionPerUser)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getPhases_DecisionPerUser()
   * @model containment="true"
   * @generated
   */
  DecisionPerUser getDecisionPerUser();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Phases#getDecisionPerUser <em>Decision Per User</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision Per User</em>' containment reference.
   * @see #getDecisionPerUser()
   * @generated
   */
  void setDecisionPerUser(DecisionPerUser value);

  /**
   * Returns the value of the '<em><b>Statistics On Exclusion Criteria</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statistics On Exclusion Criteria</em>' containment reference.
   * @see #setStatisticsOnExclusionCriteria(StatisticsOnExclusionCriteria)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getPhases_StatisticsOnExclusionCriteria()
   * @model containment="true"
   * @generated
   */
  StatisticsOnExclusionCriteria getStatisticsOnExclusionCriteria();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Phases#getStatisticsOnExclusionCriteria <em>Statistics On Exclusion Criteria</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statistics On Exclusion Criteria</em>' containment reference.
   * @see #getStatisticsOnExclusionCriteria()
   * @generated
   */
  void setStatisticsOnExclusionCriteria(StatisticsOnExclusionCriteria value);

  /**
   * Returns the value of the '<em><b>Conflict Resolution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conflict Resolution</em>' containment reference.
   * @see #setConflictResolution(ConflictResolution)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getPhases_ConflictResolution()
   * @model containment="true"
   * @generated
   */
  ConflictResolution getConflictResolution();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Phases#getConflictResolution <em>Conflict Resolution</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conflict Resolution</em>' containment reference.
   * @see #getConflictResolution()
   * @generated
   */
  void setConflictResolution(ConflictResolution value);

  /**
   * Returns the value of the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' containment reference.
   * @see #setResult(Result)
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getPhases_Result()
   * @model containment="true"
   * @generated
   */
  Result getResult();

  /**
   * Sets the value of the '{@link org.xtext.slr.reliSRS.Phases#getResult <em>Result</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Result</em>' containment reference.
   * @see #getResult()
   * @generated
   */
  void setResult(Result value);

} // Phases
