/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>RDecision</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.slr.reliSRS.ReliSRSPackage#getRDecision()
 * @model
 * @generated
 */
public enum RDecision implements Enumerator
{
  /**
   * The '<em><b>RIncluded</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RINCLUDED_VALUE
   * @generated
   * @ordered
   */
  RINCLUDED(0, "RIncluded", "Included"),

  /**
   * The '<em><b>RExcluded</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REXCLUDED_VALUE
   * @generated
   * @ordered
   */
  REXCLUDED(1, "RExcluded", "Excluded"),

  /**
   * The '<em><b>RIn Conflict</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RIN_CONFLICT_VALUE
   * @generated
   * @ordered
   */
  RIN_CONFLICT(2, "RInConflict", "In conflict"),

  /**
   * The '<em><b>RIn Review</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RIN_REVIEW_VALUE
   * @generated
   * @ordered
   */
  RIN_REVIEW(3, "RInReview", "In review"),

  /**
   * The '<em><b>RPending</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RPENDING_VALUE
   * @generated
   * @ordered
   */
  RPENDING(4, "RPending", "Pending");

  /**
   * The '<em><b>RIncluded</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RINCLUDED
   * @model name="RIncluded" literal="Included"
   * @generated
   * @ordered
   */
  public static final int RINCLUDED_VALUE = 0;

  /**
   * The '<em><b>RExcluded</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REXCLUDED
   * @model name="RExcluded" literal="Excluded"
   * @generated
   * @ordered
   */
  public static final int REXCLUDED_VALUE = 1;

  /**
   * The '<em><b>RIn Conflict</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RIN_CONFLICT
   * @model name="RInConflict" literal="In conflict"
   * @generated
   * @ordered
   */
  public static final int RIN_CONFLICT_VALUE = 2;

  /**
   * The '<em><b>RIn Review</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RIN_REVIEW
   * @model name="RInReview" literal="In review"
   * @generated
   * @ordered
   */
  public static final int RIN_REVIEW_VALUE = 3;

  /**
   * The '<em><b>RPending</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RPENDING
   * @model name="RPending" literal="Pending"
   * @generated
   * @ordered
   */
  public static final int RPENDING_VALUE = 4;

  /**
   * An array of all the '<em><b>RDecision</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final RDecision[] VALUES_ARRAY =
    new RDecision[]
    {
      RINCLUDED,
      REXCLUDED,
      RIN_CONFLICT,
      RIN_REVIEW,
      RPENDING,
    };

  /**
   * A public read-only list of all the '<em><b>RDecision</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<RDecision> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>RDecision</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RDecision get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      RDecision result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>RDecision</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RDecision getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      RDecision result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>RDecision</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static RDecision get(int value)
  {
    switch (value)
    {
      case RINCLUDED_VALUE: return RINCLUDED;
      case REXCLUDED_VALUE: return REXCLUDED;
      case RIN_CONFLICT_VALUE: return RIN_CONFLICT;
      case RIN_REVIEW_VALUE: return RIN_REVIEW;
      case RPENDING_VALUE: return RPENDING;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private RDecision(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //RDecision
