/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.slr.reliSRS.ReliSRSFactory
 * @model kind="package"
 * @generated
 */
public interface ReliSRSPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "reliSRS";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/slr/ReliSRS";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "reliSRS";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReliSRSPackage eINSTANCE = org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.ModelImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Project Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROJECT_NAME = 0;

  /**
   * The feature id for the '<em><b>Participants</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PARTICIPANTS = 1;

  /**
   * The feature id for the '<em><b>Phase</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PHASE = 2;

  /**
   * The feature id for the '<em><b>Classification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CLASSIFICATION = 3;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.ParticipantsImpl <em>Participants</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.ParticipantsImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getParticipants()
   * @generated
   */
  int PARTICIPANTS = 1;

  /**
   * The feature id for the '<em><b>Participant</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANTS__PARTICIPANT = 0;

  /**
   * The feature id for the '<em><b>Role</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANTS__ROLE = 1;

  /**
   * The number of structural features of the '<em>Participants</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARTICIPANTS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.ClassificationImpl <em>Classification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.ClassificationImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getClassification()
   * @generated
   */
  int CLASSIFICATION = 2;

  /**
   * The feature id for the '<em><b>Question</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSIFICATION__QUESTION = 0;

  /**
   * The feature id for the '<em><b>Response</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSIFICATION__RESPONSE = 1;

  /**
   * The feature id for the '<em><b>Resultat</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSIFICATION__RESULTAT = 2;

  /**
   * The number of structural features of the '<em>Classification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASSIFICATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.PhasesImpl <em>Phases</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.PhasesImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getPhases()
   * @generated
   */
  int PHASES = 3;

  /**
   * The feature id for the '<em><b>Phase Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASES__PHASE_NAME = 0;

  /**
   * The feature id for the '<em><b>Decision Per User</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASES__DECISION_PER_USER = 1;

  /**
   * The feature id for the '<em><b>Statistics On Exclusion Criteria</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASES__STATISTICS_ON_EXCLUSION_CRITERIA = 2;

  /**
   * The feature id for the '<em><b>Conflict Resolution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASES__CONFLICT_RESOLUTION = 3;

  /**
   * The feature id for the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASES__RESULT = 4;

  /**
   * The number of structural features of the '<em>Phases</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PHASES_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.DecisionPerUserImpl <em>Decision Per User</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.DecisionPerUserImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getDecisionPerUser()
   * @generated
   */
  int DECISION_PER_USER = 4;

  /**
   * The feature id for the '<em><b>DUser</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_PER_USER__DUSER = 0;

  /**
   * The feature id for the '<em><b>DIncluded</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_PER_USER__DINCLUDED = 1;

  /**
   * The feature id for the '<em><b>DExcluded</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_PER_USER__DEXCLUDED = 2;

  /**
   * The feature id for the '<em><b>DIn Conflict</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_PER_USER__DIN_CONFLICT = 3;

  /**
   * The number of structural features of the '<em>Decision Per User</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_PER_USER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.StatisticsOnExclusionCriteriaImpl <em>Statistics On Exclusion Criteria</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.StatisticsOnExclusionCriteriaImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getStatisticsOnExclusionCriteria()
   * @generated
   */
  int STATISTICS_ON_EXCLUSION_CRITERIA = 5;

  /**
   * The feature id for the '<em><b>SCriteria</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTICS_ON_EXCLUSION_CRITERIA__SCRITERIA = 0;

  /**
   * The feature id for the '<em><b>SNombre</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTICS_ON_EXCLUSION_CRITERIA__SNOMBRE = 1;

  /**
   * The feature id for the '<em><b>SPourcentage</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTICS_ON_EXCLUSION_CRITERIA__SPOURCENTAGE = 2;

  /**
   * The number of structural features of the '<em>Statistics On Exclusion Criteria</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATISTICS_ON_EXCLUSION_CRITERIA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.ConflictResolutionImpl <em>Conflict Resolution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.ConflictResolutionImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getConflictResolution()
   * @generated
   */
  int CONFLICT_RESOLUTION = 6;

  /**
   * The feature id for the '<em><b>CDecision</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFLICT_RESOLUTION__CDECISION = 0;

  /**
   * The feature id for the '<em><b>CNombre</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFLICT_RESOLUTION__CNOMBRE = 1;

  /**
   * The number of structural features of the '<em>Conflict Resolution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFLICT_RESOLUTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.impl.ResultImpl <em>Result</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.impl.ResultImpl
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getResult()
   * @generated
   */
  int RESULT = 7;

  /**
   * The feature id for the '<em><b>RTotal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__RTOTAL = 0;

  /**
   * The feature id for the '<em><b>RDecision</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__RDECISION = 1;

  /**
   * The feature id for the '<em><b>RPaper</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__RPAPER = 2;

  /**
   * The feature id for the '<em><b>RPourcentage</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT__RPOURCENTAGE = 3;

  /**
   * The number of structural features of the '<em>Result</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RESULT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.CDecision <em>CDecision</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.CDecision
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getCDecision()
   * @generated
   */
  int CDECISION = 8;

  /**
   * The meta object id for the '{@link org.xtext.slr.reliSRS.RDecision <em>RDecision</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.slr.reliSRS.RDecision
   * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getRDecision()
   * @generated
   */
  int RDECISION = 9;


  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.slr.reliSRS.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.slr.reliSRS.Model#getProjectName <em>Project Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Project Name</em>'.
   * @see org.xtext.slr.reliSRS.Model#getProjectName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_ProjectName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.slr.reliSRS.Model#getParticipants <em>Participants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Participants</em>'.
   * @see org.xtext.slr.reliSRS.Model#getParticipants()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Participants();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.slr.reliSRS.Model#getPhase <em>Phase</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Phase</em>'.
   * @see org.xtext.slr.reliSRS.Model#getPhase()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Phase();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.slr.reliSRS.Model#getClassification <em>Classification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Classification</em>'.
   * @see org.xtext.slr.reliSRS.Model#getClassification()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Classification();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.Participants <em>Participants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Participants</em>'.
   * @see org.xtext.slr.reliSRS.Participants
   * @generated
   */
  EClass getParticipants();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Participants#getParticipant <em>Participant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Participant</em>'.
   * @see org.xtext.slr.reliSRS.Participants#getParticipant()
   * @see #getParticipants()
   * @generated
   */
  EAttribute getParticipants_Participant();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Participants#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Role</em>'.
   * @see org.xtext.slr.reliSRS.Participants#getRole()
   * @see #getParticipants()
   * @generated
   */
  EAttribute getParticipants_Role();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.Classification <em>Classification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Classification</em>'.
   * @see org.xtext.slr.reliSRS.Classification
   * @generated
   */
  EClass getClassification();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Classification#getQuestion <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Question</em>'.
   * @see org.xtext.slr.reliSRS.Classification#getQuestion()
   * @see #getClassification()
   * @generated
   */
  EAttribute getClassification_Question();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Classification#getResponse <em>Response</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Response</em>'.
   * @see org.xtext.slr.reliSRS.Classification#getResponse()
   * @see #getClassification()
   * @generated
   */
  EAttribute getClassification_Response();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Classification#getResultat <em>Resultat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Resultat</em>'.
   * @see org.xtext.slr.reliSRS.Classification#getResultat()
   * @see #getClassification()
   * @generated
   */
  EAttribute getClassification_Resultat();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.Phases <em>Phases</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Phases</em>'.
   * @see org.xtext.slr.reliSRS.Phases
   * @generated
   */
  EClass getPhases();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.slr.reliSRS.Phases#getPhaseName <em>Phase Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Phase Name</em>'.
   * @see org.xtext.slr.reliSRS.Phases#getPhaseName()
   * @see #getPhases()
   * @generated
   */
  EAttribute getPhases_PhaseName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.slr.reliSRS.Phases#getDecisionPerUser <em>Decision Per User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decision Per User</em>'.
   * @see org.xtext.slr.reliSRS.Phases#getDecisionPerUser()
   * @see #getPhases()
   * @generated
   */
  EReference getPhases_DecisionPerUser();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.slr.reliSRS.Phases#getStatisticsOnExclusionCriteria <em>Statistics On Exclusion Criteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Statistics On Exclusion Criteria</em>'.
   * @see org.xtext.slr.reliSRS.Phases#getStatisticsOnExclusionCriteria()
   * @see #getPhases()
   * @generated
   */
  EReference getPhases_StatisticsOnExclusionCriteria();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.slr.reliSRS.Phases#getConflictResolution <em>Conflict Resolution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conflict Resolution</em>'.
   * @see org.xtext.slr.reliSRS.Phases#getConflictResolution()
   * @see #getPhases()
   * @generated
   */
  EReference getPhases_ConflictResolution();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.slr.reliSRS.Phases#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Result</em>'.
   * @see org.xtext.slr.reliSRS.Phases#getResult()
   * @see #getPhases()
   * @generated
   */
  EReference getPhases_Result();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.DecisionPerUser <em>Decision Per User</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision Per User</em>'.
   * @see org.xtext.slr.reliSRS.DecisionPerUser
   * @generated
   */
  EClass getDecisionPerUser();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.DecisionPerUser#getDUser <em>DUser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>DUser</em>'.
   * @see org.xtext.slr.reliSRS.DecisionPerUser#getDUser()
   * @see #getDecisionPerUser()
   * @generated
   */
  EAttribute getDecisionPerUser_DUser();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.DecisionPerUser#getDIncluded <em>DIncluded</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>DIncluded</em>'.
   * @see org.xtext.slr.reliSRS.DecisionPerUser#getDIncluded()
   * @see #getDecisionPerUser()
   * @generated
   */
  EAttribute getDecisionPerUser_DIncluded();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.DecisionPerUser#getDExcluded <em>DExcluded</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>DExcluded</em>'.
   * @see org.xtext.slr.reliSRS.DecisionPerUser#getDExcluded()
   * @see #getDecisionPerUser()
   * @generated
   */
  EAttribute getDecisionPerUser_DExcluded();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.DecisionPerUser#getDInConflict <em>DIn Conflict</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>DIn Conflict</em>'.
   * @see org.xtext.slr.reliSRS.DecisionPerUser#getDInConflict()
   * @see #getDecisionPerUser()
   * @generated
   */
  EAttribute getDecisionPerUser_DInConflict();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria <em>Statistics On Exclusion Criteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statistics On Exclusion Criteria</em>'.
   * @see org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria
   * @generated
   */
  EClass getStatisticsOnExclusionCriteria();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSCriteria <em>SCriteria</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>SCriteria</em>'.
   * @see org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSCriteria()
   * @see #getStatisticsOnExclusionCriteria()
   * @generated
   */
  EAttribute getStatisticsOnExclusionCriteria_SCriteria();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSNombre <em>SNombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>SNombre</em>'.
   * @see org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSNombre()
   * @see #getStatisticsOnExclusionCriteria()
   * @generated
   */
  EAttribute getStatisticsOnExclusionCriteria_SNombre();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSPourcentage <em>SPourcentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>SPourcentage</em>'.
   * @see org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSPourcentage()
   * @see #getStatisticsOnExclusionCriteria()
   * @generated
   */
  EAttribute getStatisticsOnExclusionCriteria_SPourcentage();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.ConflictResolution <em>Conflict Resolution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conflict Resolution</em>'.
   * @see org.xtext.slr.reliSRS.ConflictResolution
   * @generated
   */
  EClass getConflictResolution();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.ConflictResolution#getCDecision <em>CDecision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>CDecision</em>'.
   * @see org.xtext.slr.reliSRS.ConflictResolution#getCDecision()
   * @see #getConflictResolution()
   * @generated
   */
  EAttribute getConflictResolution_CDecision();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.ConflictResolution#getCNombre <em>CNombre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>CNombre</em>'.
   * @see org.xtext.slr.reliSRS.ConflictResolution#getCNombre()
   * @see #getConflictResolution()
   * @generated
   */
  EAttribute getConflictResolution_CNombre();

  /**
   * Returns the meta object for class '{@link org.xtext.slr.reliSRS.Result <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Result</em>'.
   * @see org.xtext.slr.reliSRS.Result
   * @generated
   */
  EClass getResult();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.slr.reliSRS.Result#getRTotal <em>RTotal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>RTotal</em>'.
   * @see org.xtext.slr.reliSRS.Result#getRTotal()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_RTotal();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Result#getRDecision <em>RDecision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>RDecision</em>'.
   * @see org.xtext.slr.reliSRS.Result#getRDecision()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_RDecision();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Result#getRPaper <em>RPaper</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>RPaper</em>'.
   * @see org.xtext.slr.reliSRS.Result#getRPaper()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_RPaper();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.slr.reliSRS.Result#getRPourcentage <em>RPourcentage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>RPourcentage</em>'.
   * @see org.xtext.slr.reliSRS.Result#getRPourcentage()
   * @see #getResult()
   * @generated
   */
  EAttribute getResult_RPourcentage();

  /**
   * Returns the meta object for enum '{@link org.xtext.slr.reliSRS.CDecision <em>CDecision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>CDecision</em>'.
   * @see org.xtext.slr.reliSRS.CDecision
   * @generated
   */
  EEnum getCDecision();

  /**
   * Returns the meta object for enum '{@link org.xtext.slr.reliSRS.RDecision <em>RDecision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>RDecision</em>'.
   * @see org.xtext.slr.reliSRS.RDecision
   * @generated
   */
  EEnum getRDecision();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ReliSRSFactory getReliSRSFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.ModelImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Project Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__PROJECT_NAME = eINSTANCE.getModel_ProjectName();

    /**
     * The meta object literal for the '<em><b>Participants</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PARTICIPANTS = eINSTANCE.getModel_Participants();

    /**
     * The meta object literal for the '<em><b>Phase</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PHASE = eINSTANCE.getModel_Phase();

    /**
     * The meta object literal for the '<em><b>Classification</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CLASSIFICATION = eINSTANCE.getModel_Classification();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.ParticipantsImpl <em>Participants</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.ParticipantsImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getParticipants()
     * @generated
     */
    EClass PARTICIPANTS = eINSTANCE.getParticipants();

    /**
     * The meta object literal for the '<em><b>Participant</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANTS__PARTICIPANT = eINSTANCE.getParticipants_Participant();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARTICIPANTS__ROLE = eINSTANCE.getParticipants_Role();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.ClassificationImpl <em>Classification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.ClassificationImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getClassification()
     * @generated
     */
    EClass CLASSIFICATION = eINSTANCE.getClassification();

    /**
     * The meta object literal for the '<em><b>Question</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASSIFICATION__QUESTION = eINSTANCE.getClassification_Question();

    /**
     * The meta object literal for the '<em><b>Response</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASSIFICATION__RESPONSE = eINSTANCE.getClassification_Response();

    /**
     * The meta object literal for the '<em><b>Resultat</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASSIFICATION__RESULTAT = eINSTANCE.getClassification_Resultat();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.PhasesImpl <em>Phases</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.PhasesImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getPhases()
     * @generated
     */
    EClass PHASES = eINSTANCE.getPhases();

    /**
     * The meta object literal for the '<em><b>Phase Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PHASES__PHASE_NAME = eINSTANCE.getPhases_PhaseName();

    /**
     * The meta object literal for the '<em><b>Decision Per User</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASES__DECISION_PER_USER = eINSTANCE.getPhases_DecisionPerUser();

    /**
     * The meta object literal for the '<em><b>Statistics On Exclusion Criteria</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASES__STATISTICS_ON_EXCLUSION_CRITERIA = eINSTANCE.getPhases_StatisticsOnExclusionCriteria();

    /**
     * The meta object literal for the '<em><b>Conflict Resolution</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASES__CONFLICT_RESOLUTION = eINSTANCE.getPhases_ConflictResolution();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PHASES__RESULT = eINSTANCE.getPhases_Result();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.DecisionPerUserImpl <em>Decision Per User</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.DecisionPerUserImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getDecisionPerUser()
     * @generated
     */
    EClass DECISION_PER_USER = eINSTANCE.getDecisionPerUser();

    /**
     * The meta object literal for the '<em><b>DUser</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_PER_USER__DUSER = eINSTANCE.getDecisionPerUser_DUser();

    /**
     * The meta object literal for the '<em><b>DIncluded</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_PER_USER__DINCLUDED = eINSTANCE.getDecisionPerUser_DIncluded();

    /**
     * The meta object literal for the '<em><b>DExcluded</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_PER_USER__DEXCLUDED = eINSTANCE.getDecisionPerUser_DExcluded();

    /**
     * The meta object literal for the '<em><b>DIn Conflict</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION_PER_USER__DIN_CONFLICT = eINSTANCE.getDecisionPerUser_DInConflict();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.StatisticsOnExclusionCriteriaImpl <em>Statistics On Exclusion Criteria</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.StatisticsOnExclusionCriteriaImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getStatisticsOnExclusionCriteria()
     * @generated
     */
    EClass STATISTICS_ON_EXCLUSION_CRITERIA = eINSTANCE.getStatisticsOnExclusionCriteria();

    /**
     * The meta object literal for the '<em><b>SCriteria</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTICS_ON_EXCLUSION_CRITERIA__SCRITERIA = eINSTANCE.getStatisticsOnExclusionCriteria_SCriteria();

    /**
     * The meta object literal for the '<em><b>SNombre</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTICS_ON_EXCLUSION_CRITERIA__SNOMBRE = eINSTANCE.getStatisticsOnExclusionCriteria_SNombre();

    /**
     * The meta object literal for the '<em><b>SPourcentage</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATISTICS_ON_EXCLUSION_CRITERIA__SPOURCENTAGE = eINSTANCE.getStatisticsOnExclusionCriteria_SPourcentage();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.ConflictResolutionImpl <em>Conflict Resolution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.ConflictResolutionImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getConflictResolution()
     * @generated
     */
    EClass CONFLICT_RESOLUTION = eINSTANCE.getConflictResolution();

    /**
     * The meta object literal for the '<em><b>CDecision</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFLICT_RESOLUTION__CDECISION = eINSTANCE.getConflictResolution_CDecision();

    /**
     * The meta object literal for the '<em><b>CNombre</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFLICT_RESOLUTION__CNOMBRE = eINSTANCE.getConflictResolution_CNombre();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.impl.ResultImpl <em>Result</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.impl.ResultImpl
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getResult()
     * @generated
     */
    EClass RESULT = eINSTANCE.getResult();

    /**
     * The meta object literal for the '<em><b>RTotal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__RTOTAL = eINSTANCE.getResult_RTotal();

    /**
     * The meta object literal for the '<em><b>RDecision</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__RDECISION = eINSTANCE.getResult_RDecision();

    /**
     * The meta object literal for the '<em><b>RPaper</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__RPAPER = eINSTANCE.getResult_RPaper();

    /**
     * The meta object literal for the '<em><b>RPourcentage</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RESULT__RPOURCENTAGE = eINSTANCE.getResult_RPourcentage();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.CDecision <em>CDecision</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.CDecision
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getCDecision()
     * @generated
     */
    EEnum CDECISION = eINSTANCE.getCDecision();

    /**
     * The meta object literal for the '{@link org.xtext.slr.reliSRS.RDecision <em>RDecision</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.slr.reliSRS.RDecision
     * @see org.xtext.slr.reliSRS.impl.ReliSRSPackageImpl#getRDecision()
     * @generated
     */
    EEnum RDECISION = eINSTANCE.getRDecision();

  }

} //ReliSRSPackage
