/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.slr.reliSRS.ReliSRSPackage
 * @generated
 */
public interface ReliSRSFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReliSRSFactory eINSTANCE = org.xtext.slr.reliSRS.impl.ReliSRSFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Participants</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Participants</em>'.
   * @generated
   */
  Participants createParticipants();

  /**
   * Returns a new object of class '<em>Classification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Classification</em>'.
   * @generated
   */
  Classification createClassification();

  /**
   * Returns a new object of class '<em>Phases</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Phases</em>'.
   * @generated
   */
  Phases createPhases();

  /**
   * Returns a new object of class '<em>Decision Per User</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Decision Per User</em>'.
   * @generated
   */
  DecisionPerUser createDecisionPerUser();

  /**
   * Returns a new object of class '<em>Statistics On Exclusion Criteria</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statistics On Exclusion Criteria</em>'.
   * @generated
   */
  StatisticsOnExclusionCriteria createStatisticsOnExclusionCriteria();

  /**
   * Returns a new object of class '<em>Conflict Resolution</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Conflict Resolution</em>'.
   * @generated
   */
  ConflictResolution createConflictResolution();

  /**
   * Returns a new object of class '<em>Result</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Result</em>'.
   * @generated
   */
  Result createResult();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReliSRSPackage getReliSRSPackage();

} //ReliSRSFactory
