/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statistics On Exclusion Criteria</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSCriteria <em>SCriteria</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSNombre <em>SNombre</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.StatisticsOnExclusionCriteria#getSPourcentage <em>SPourcentage</em>}</li>
 * </ul>
 *
 * @see org.xtext.slr.reliSRS.ReliSRSPackage#getStatisticsOnExclusionCriteria()
 * @model
 * @generated
 */
public interface StatisticsOnExclusionCriteria extends EObject
{
  /**
   * Returns the value of the '<em><b>SCriteria</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SCriteria</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getStatisticsOnExclusionCriteria_SCriteria()
   * @model unique="false"
   * @generated
   */
  EList<String> getSCriteria();

  /**
   * Returns the value of the '<em><b>SNombre</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SNombre</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getStatisticsOnExclusionCriteria_SNombre()
   * @model unique="false"
   * @generated
   */
  EList<String> getSNombre();

  /**
   * Returns the value of the '<em><b>SPourcentage</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SPourcentage</em>' attribute list.
   * @see org.xtext.slr.reliSRS.ReliSRSPackage#getStatisticsOnExclusionCriteria_SPourcentage()
   * @model unique="false"
   * @generated
   */
  EList<String> getSPourcentage();

} // StatisticsOnExclusionCriteria
