/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.ide;

import org.xtext.slr.ide.AbstractReliSRSIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ReliSRSIdeModule extends AbstractReliSRSIdeModule {
}
