/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.slr.ReliSRSRuntimeModule;
import org.xtext.slr.ReliSRSStandaloneSetup;
import org.xtext.slr.ide.ReliSRSIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ReliSRSIdeSetup extends ReliSRSStandaloneSetup {
  @Override
  public Injector createInjector() {
    ReliSRSRuntimeModule _reliSRSRuntimeModule = new ReliSRSRuntimeModule();
    ReliSRSIdeModule _reliSRSIdeModule = new ReliSRSIdeModule();
    return Guice.createInjector(Modules2.mixin(_reliSRSRuntimeModule, _reliSRSIdeModule));
  }
}
