/*
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.slr.services.ReliSRSGrammarAccess;

@SuppressWarnings("all")
public class ReliSRSSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ReliSRSGrammarAccess grammarAccess;
	protected AbstractElementAlias match_ConflictResolution___C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1__a;
	protected AbstractElementAlias match_ConflictResolution___LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5__a;
	protected AbstractElementAlias match_ConflictResolution___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3__a;
	protected AbstractElementAlias match_DecisionPerUser___D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3__a;
	protected AbstractElementAlias match_DecisionPerUser___D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5__a;
	protected AbstractElementAlias match_DecisionPerUser___D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1__a;
	protected AbstractElementAlias match_DecisionPerUser___LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9__a;
	protected AbstractElementAlias match_DecisionPerUser___RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7__a;
	protected AbstractElementAlias match_Model_PhaseKeyword_3_0_a;
	protected AbstractElementAlias match_Model_PhaseKeyword_3_0_p;
	protected AbstractElementAlias match_Participants___LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3_RightCurlyBracketKeyword_1_5__a;
	protected AbstractElementAlias match_Participants___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3__a;
	protected AbstractElementAlias match_Participants___RoleKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1__a;
	protected AbstractElementAlias match_Result___LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7__a;
	protected AbstractElementAlias match_Result___R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1__a;
	protected AbstractElementAlias match_Result___R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3__a;
	protected AbstractElementAlias match_Result___RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5__a;
	protected AbstractElementAlias match_StatisticsOnExclusionCriteria___LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7__a;
	protected AbstractElementAlias match_StatisticsOnExclusionCriteria___RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5__a;
	protected AbstractElementAlias match_StatisticsOnExclusionCriteria___S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1__a;
	protected AbstractElementAlias match_StatisticsOnExclusionCriteria___S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3__a;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ReliSRSGrammarAccess) access;
		match_ConflictResolution___C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getC_NombreKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getRightCurlyBracketKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getC_DecisionKeyword_1_1()));
		match_ConflictResolution___LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getC_DecisionKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getC_NombreKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getRightCurlyBracketKeyword_1_5()));
		match_ConflictResolution___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getRightCurlyBracketKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getC_DecisionKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getConflictResolutionAccess().getC_NombreKeyword_1_3()));
		match_DecisionPerUser___D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_ExcludedKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_InConfclictKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getRightCurlyBracketKeyword_1_9()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_UserKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_IncludedKeyword_1_3()));
		match_DecisionPerUser___D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_InConfclictKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getRightCurlyBracketKeyword_1_9()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_UserKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_IncludedKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_ExcludedKeyword_1_5()));
		match_DecisionPerUser___D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_IncludedKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_ExcludedKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_InConfclictKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getRightCurlyBracketKeyword_1_9()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_UserKeyword_1_1()));
		match_DecisionPerUser___LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_UserKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_IncludedKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_ExcludedKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_InConfclictKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getRightCurlyBracketKeyword_1_9()));
		match_DecisionPerUser___RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getRightCurlyBracketKeyword_1_9()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_UserKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_IncludedKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_ExcludedKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getDecisionPerUserAccess().getD_InConfclictKeyword_1_7()));
		match_Model_PhaseKeyword_3_0_a = new TokenAlias(true, true, grammarAccess.getModelAccess().getPhaseKeyword_3_0());
		match_Model_PhaseKeyword_3_0_p = new TokenAlias(true, false, grammarAccess.getModelAccess().getPhaseKeyword_3_0());
		match_Participants___LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3_RightCurlyBracketKeyword_1_5__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getParticipantKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getRoleKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getRightCurlyBracketKeyword_1_5()));
		match_Participants___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getRightCurlyBracketKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getParticipantKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getRoleKeyword_1_3()));
		match_Participants___RoleKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getRoleKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getRightCurlyBracketKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getParticipantsAccess().getParticipantKeyword_1_1()));
		match_Result___LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getResultAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_DecisionKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PaperKeyword_3_3()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PourcentageKeyword_3_5()), new TokenAlias(false, false, grammarAccess.getResultAccess().getRightCurlyBracketKeyword_3_7()));
		match_Result___R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PaperKeyword_3_3()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PourcentageKeyword_3_5()), new TokenAlias(false, false, grammarAccess.getResultAccess().getRightCurlyBracketKeyword_3_7()), new TokenAlias(false, false, grammarAccess.getResultAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_DecisionKeyword_3_1()));
		match_Result___R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PourcentageKeyword_3_5()), new TokenAlias(false, false, grammarAccess.getResultAccess().getRightCurlyBracketKeyword_3_7()), new TokenAlias(false, false, grammarAccess.getResultAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_DecisionKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PaperKeyword_3_3()));
		match_Result___RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getResultAccess().getRightCurlyBracketKeyword_3_7()), new TokenAlias(false, false, grammarAccess.getResultAccess().getLeftCurlyBracketKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_DecisionKeyword_3_1()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PaperKeyword_3_3()), new TokenAlias(false, false, grammarAccess.getResultAccess().getR_PourcentageKeyword_3_5()));
		match_StatisticsOnExclusionCriteria___LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_CriteriaKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_NombreKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_PourcentageKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getRightCurlyBracketKeyword_1_7()));
		match_StatisticsOnExclusionCriteria___RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getRightCurlyBracketKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_CriteriaKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_NombreKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_PourcentageKeyword_1_5()));
		match_StatisticsOnExclusionCriteria___S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_NombreKeyword_1_3()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_PourcentageKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getRightCurlyBracketKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_CriteriaKeyword_1_1()));
		match_StatisticsOnExclusionCriteria___S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_PourcentageKeyword_1_5()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getRightCurlyBracketKeyword_1_7()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getLeftCurlyBracketKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_CriteriaKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getStatisticsOnExclusionCriteriaAccess().getS_NombreKeyword_1_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_ConflictResolution___C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1__a.equals(syntax))
				emit_ConflictResolution___C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ConflictResolution___LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5__a.equals(syntax))
				emit_ConflictResolution___LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ConflictResolution___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3__a.equals(syntax))
				emit_ConflictResolution___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DecisionPerUser___D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3__a.equals(syntax))
				emit_DecisionPerUser___D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DecisionPerUser___D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5__a.equals(syntax))
				emit_DecisionPerUser___D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DecisionPerUser___D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1__a.equals(syntax))
				emit_DecisionPerUser___D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DecisionPerUser___LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9__a.equals(syntax))
				emit_DecisionPerUser___LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DecisionPerUser___RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7__a.equals(syntax))
				emit_DecisionPerUser___RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Model_PhaseKeyword_3_0_a.equals(syntax))
				emit_Model_PhaseKeyword_3_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Model_PhaseKeyword_3_0_p.equals(syntax))
				emit_Model_PhaseKeyword_3_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Participants___LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3_RightCurlyBracketKeyword_1_5__a.equals(syntax))
				emit_Participants___LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3_RightCurlyBracketKeyword_1_5__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Participants___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3__a.equals(syntax))
				emit_Participants___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Participants___RoleKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1__a.equals(syntax))
				emit_Participants___RoleKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Result___LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7__a.equals(syntax))
				emit_Result___LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Result___R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1__a.equals(syntax))
				emit_Result___R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Result___R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3__a.equals(syntax))
				emit_Result___R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Result___RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5__a.equals(syntax))
				emit_Result___RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatisticsOnExclusionCriteria___LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7__a.equals(syntax))
				emit_StatisticsOnExclusionCriteria___LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatisticsOnExclusionCriteria___RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5__a.equals(syntax))
				emit_StatisticsOnExclusionCriteria___RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatisticsOnExclusionCriteria___S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1__a.equals(syntax))
				emit_StatisticsOnExclusionCriteria___S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StatisticsOnExclusionCriteria___S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3__a.equals(syntax))
				emit_StatisticsOnExclusionCriteria___S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('C_Nombre:' '}' '{' 'C_Decision:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'C_Decision:' (ambiguity) cDecision+=CDecision
	 *     cDecision+=CDecision (ambiguity) cDecision+=CDecision
	 *     cNombre+=CNombre '}' '{' 'C_Decision:' (ambiguity) cDecision+=CDecision
	 */
	protected void emit_ConflictResolution___C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' 'C_Decision:' 'C_Nombre:' '}')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     cDecision+=CDecision 'C_Nombre:' '}' (ambiguity) (rule end)
	 *     cNombre+=CNombre '}' (ambiguity) (rule end)
	 */
	protected void emit_ConflictResolution___LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3_RightCurlyBracketKeyword_1_5__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}' '{' 'C_Decision:' 'C_Nombre:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'C_Decision:' 'C_Nombre:' (ambiguity) cNombre+=CNombre
	 *     cDecision+=CDecision 'C_Nombre:' (ambiguity) cNombre+=CNombre
	 *     cNombre+=CNombre (ambiguity) cNombre+=CNombre
	 */
	protected void emit_ConflictResolution___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_C_DecisionKeyword_1_1_C_NombreKeyword_1_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         'D_Excluded:' 
	  *         'D_InConfclict:' 
	  *         '}' 
	  *         '{' 
	  *         'D_User:' 
	  *         'D_Included:'
	  *     )*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'D_User:' 'D_Included:' (ambiguity) dIncluded+=DIncluded
	 *     dExcluded+=DExcluded 'D_InConfclict:' '}' '{' 'D_User:' 'D_Included:' (ambiguity) dIncluded+=DIncluded
	 *     dInConflict+=DInConflict '}' '{' 'D_User:' 'D_Included:' (ambiguity) dIncluded+=DIncluded
	 *     dIncluded+=DIncluded (ambiguity) dIncluded+=DIncluded
	 *     dUser+=DUser 'D_Included:' (ambiguity) dIncluded+=DIncluded
	 */
	protected void emit_DecisionPerUser___D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         'D_InConfclict:' 
	  *         '}' 
	  *         '{' 
	  *         'D_User:' 
	  *         'D_Included:' 
	  *         'D_Excluded:'
	  *     )*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'D_User:' 'D_Included:' 'D_Excluded:' (ambiguity) dExcluded+=DExcluded
	 *     dExcluded+=DExcluded (ambiguity) dExcluded+=DExcluded
	 *     dInConflict+=DInConflict '}' '{' 'D_User:' 'D_Included:' 'D_Excluded:' (ambiguity) dExcluded+=DExcluded
	 *     dIncluded+=DIncluded 'D_Excluded:' (ambiguity) dExcluded+=DExcluded
	 *     dUser+=DUser 'D_Included:' 'D_Excluded:' (ambiguity) dExcluded+=DExcluded
	 */
	protected void emit_DecisionPerUser___D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         'D_Included:' 
	  *         'D_Excluded:' 
	  *         'D_InConfclict:' 
	  *         '}' 
	  *         '{' 
	  *         'D_User:'
	  *     )*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'D_User:' (ambiguity) dUser+=DUser
	 *     dExcluded+=DExcluded 'D_InConfclict:' '}' '{' 'D_User:' (ambiguity) dUser+=DUser
	 *     dInConflict+=DInConflict '}' '{' 'D_User:' (ambiguity) dUser+=DUser
	 *     dIncluded+=DIncluded 'D_Excluded:' 'D_InConfclict:' '}' '{' 'D_User:' (ambiguity) dUser+=DUser
	 *     dUser+=DUser (ambiguity) dUser+=DUser
	 */
	protected void emit_DecisionPerUser___D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         '{' 
	  *         'D_User:' 
	  *         'D_Included:' 
	  *         'D_Excluded:' 
	  *         'D_InConfclict:' 
	  *         '}'
	  *     )*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     dExcluded+=DExcluded 'D_InConfclict:' '}' (ambiguity) (rule end)
	 *     dInConflict+=DInConflict '}' (ambiguity) (rule end)
	 *     dIncluded+=DIncluded 'D_Excluded:' 'D_InConfclict:' '}' (ambiguity) (rule end)
	 *     dUser+=DUser 'D_Included:' 'D_Excluded:' 'D_InConfclict:' '}' (ambiguity) (rule end)
	 */
	protected void emit_DecisionPerUser___LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7_RightCurlyBracketKeyword_1_9__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (
	  *         '}' 
	  *         '{' 
	  *         'D_User:' 
	  *         'D_Included:' 
	  *         'D_Excluded:' 
	  *         'D_InConfclict:'
	  *     )*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'D_User:' 'D_Included:' 'D_Excluded:' 'D_InConfclict:' (ambiguity) dInConflict+=DInConflict
	 *     dExcluded+=DExcluded 'D_InConfclict:' (ambiguity) dInConflict+=DInConflict
	 *     dInConflict+=DInConflict (ambiguity) dInConflict+=DInConflict
	 *     dIncluded+=DIncluded 'D_Excluded:' 'D_InConfclict:' (ambiguity) dInConflict+=DInConflict
	 *     dUser+=DUser 'D_Included:' 'D_Excluded:' 'D_InConfclict:' (ambiguity) dInConflict+=DInConflict
	 */
	protected void emit_DecisionPerUser___RightCurlyBracketKeyword_1_9_LeftCurlyBracketKeyword_1_0_D_UserKeyword_1_1_D_IncludedKeyword_1_3_D_ExcludedKeyword_1_5_D_InConfclictKeyword_1_7__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Phase:'*
	 *
	 * This ambiguous syntax occurs at:
	 *     participants=Participants (ambiguity) 'Classification:' classification=Classification
	 *     phase+=Phases (ambiguity) 'Classification:' classification=Classification
	 *     phase+=Phases (ambiguity) phase+=Phases
	 */
	protected void emit_Model_PhaseKeyword_3_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Phase:'+
	 *
	 * This ambiguous syntax occurs at:
	 *     participants=Participants (ambiguity) phase+=Phases
	 */
	protected void emit_Model_PhaseKeyword_3_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' 'Participant:' 'Role:' '}')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     participant+=Participant 'Role:' '}' (ambiguity) (rule end)
	 *     role+=Role '}' (ambiguity) (rule end)
	 */
	protected void emit_Participants___LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3_RightCurlyBracketKeyword_1_5__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}' '{' 'Participant:' 'Role:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'Participant:' 'Role:' (ambiguity) role+=Role
	 *     participant+=Participant 'Role:' (ambiguity) role+=Role
	 *     role+=Role (ambiguity) role+=Role
	 */
	protected void emit_Participants___RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1_RoleKeyword_1_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('Role:' '}' '{' 'Participant:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'Participant:' (ambiguity) participant+=Participant
	 *     participant+=Participant (ambiguity) participant+=Participant
	 *     role+=Role '}' '{' 'Participant:' (ambiguity) participant+=Participant
	 */
	protected void emit_Participants___RoleKeyword_1_3_RightCurlyBracketKeyword_1_5_LeftCurlyBracketKeyword_1_0_ParticipantKeyword_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' 'R_Decision:' 'R_Paper:' 'R_Pourcentage:' '}')*
	 *
	 * This ambiguous syntax occurs at:
	 *     rDecision+=RDecision 'R_Paper:' 'R_Pourcentage:' '}' (ambiguity) (rule end)
	 *     rPaper+=RPaper 'R_Pourcentage:' '}' (ambiguity) (rule end)
	 *     rPourcentage+=RPourcentage '}' (ambiguity) (rule end)
	 *     rTotal=RTotal (ambiguity) (rule end)
	 */
	protected void emit_Result___LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('R_Paper:' 'R_Pourcentage:' '}' '{' 'R_Decision:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     rDecision+=RDecision (ambiguity) rDecision+=RDecision
	 *     rPaper+=RPaper 'R_Pourcentage:' '}' '{' 'R_Decision:' (ambiguity) rDecision+=RDecision
	 *     rPourcentage+=RPourcentage '}' '{' 'R_Decision:' (ambiguity) rDecision+=RDecision
	 *     rTotal=RTotal '{' 'R_Decision:' (ambiguity) rDecision+=RDecision
	 */
	protected void emit_Result___R_PaperKeyword_3_3_R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('R_Pourcentage:' '}' '{' 'R_Decision:' 'R_Paper:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     rDecision+=RDecision 'R_Paper:' (ambiguity) rPaper+=RPaper
	 *     rPaper+=RPaper (ambiguity) rPaper+=RPaper
	 *     rPourcentage+=RPourcentage '}' '{' 'R_Decision:' 'R_Paper:' (ambiguity) rPaper+=RPaper
	 *     rTotal=RTotal '{' 'R_Decision:' 'R_Paper:' (ambiguity) rPaper+=RPaper
	 */
	protected void emit_Result___R_PourcentageKeyword_3_5_RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}' '{' 'R_Decision:' 'R_Paper:' 'R_Pourcentage:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     rDecision+=RDecision 'R_Paper:' 'R_Pourcentage:' (ambiguity) rPourcentage+=RPourcentage
	 *     rPaper+=RPaper 'R_Pourcentage:' (ambiguity) rPourcentage+=RPourcentage
	 *     rPourcentage+=RPourcentage (ambiguity) rPourcentage+=RPourcentage
	 *     rTotal=RTotal '{' 'R_Decision:' 'R_Paper:' 'R_Pourcentage:' (ambiguity) rPourcentage+=RPourcentage
	 */
	protected void emit_Result___RightCurlyBracketKeyword_3_7_LeftCurlyBracketKeyword_3_0_R_DecisionKeyword_3_1_R_PaperKeyword_3_3_R_PourcentageKeyword_3_5__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' 'S_Criteria:' 'S_Nombre:' 'S_Pourcentage:' '}')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 *     sCriteria+=SCriteria 'S_Nombre:' 'S_Pourcentage:' '}' (ambiguity) (rule end)
	 *     sNombre+=SNombre 'S_Pourcentage:' '}' (ambiguity) (rule end)
	 *     sPourcentage+=SPourcentage '}' (ambiguity) (rule end)
	 */
	protected void emit_StatisticsOnExclusionCriteria___LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('}' '{' 'S_Criteria:' 'S_Nombre:' 'S_Pourcentage:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'S_Criteria:' 'S_Nombre:' 'S_Pourcentage:' (ambiguity) sPourcentage+=SPourcentage
	 *     sCriteria+=SCriteria 'S_Nombre:' 'S_Pourcentage:' (ambiguity) sPourcentage+=SPourcentage
	 *     sNombre+=SNombre 'S_Pourcentage:' (ambiguity) sPourcentage+=SPourcentage
	 *     sPourcentage+=SPourcentage (ambiguity) sPourcentage+=SPourcentage
	 */
	protected void emit_StatisticsOnExclusionCriteria___RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3_S_PourcentageKeyword_1_5__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('S_Nombre:' 'S_Pourcentage:' '}' '{' 'S_Criteria:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'S_Criteria:' (ambiguity) sCriteria+=SCriteria
	 *     sCriteria+=SCriteria (ambiguity) sCriteria+=SCriteria
	 *     sNombre+=SNombre 'S_Pourcentage:' '}' '{' 'S_Criteria:' (ambiguity) sCriteria+=SCriteria
	 *     sPourcentage+=SPourcentage '}' '{' 'S_Criteria:' (ambiguity) sCriteria+=SCriteria
	 */
	protected void emit_StatisticsOnExclusionCriteria___S_NombreKeyword_1_3_S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('S_Pourcentage:' '}' '{' 'S_Criteria:' 'S_Nombre:')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '{' 'S_Criteria:' 'S_Nombre:' (ambiguity) sNombre+=SNombre
	 *     sCriteria+=SCriteria 'S_Nombre:' (ambiguity) sNombre+=SNombre
	 *     sNombre+=SNombre (ambiguity) sNombre+=SNombre
	 *     sPourcentage+=SPourcentage '}' '{' 'S_Criteria:' 'S_Nombre:' (ambiguity) sNombre+=SNombre
	 */
	protected void emit_StatisticsOnExclusionCriteria___S_PourcentageKeyword_1_5_RightCurlyBracketKeyword_1_7_LeftCurlyBracketKeyword_1_0_S_CriteriaKeyword_1_1_S_NombreKeyword_1_3__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
