/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.validation;

import org.xtext.slr.validation.AbstractReliSRSValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ReliSRSValidator extends AbstractReliSRSValidator {
}
