/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.reliSRS.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.slr.reliSRS.Participants;
import org.xtext.slr.reliSRS.ReliSRSPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Participants</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.slr.reliSRS.impl.ParticipantsImpl#getParticipant <em>Participant</em>}</li>
 *   <li>{@link org.xtext.slr.reliSRS.impl.ParticipantsImpl#getRole <em>Role</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParticipantsImpl extends MinimalEObjectImpl.Container implements Participants
{
  /**
   * The cached value of the '{@link #getParticipant() <em>Participant</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParticipant()
   * @generated
   * @ordered
   */
  protected EList<String> participant;

  /**
   * The cached value of the '{@link #getRole() <em>Role</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole()
   * @generated
   * @ordered
   */
  protected EList<String> role;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParticipantsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReliSRSPackage.Literals.PARTICIPANTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getParticipant()
  {
    if (participant == null)
    {
      participant = new EDataTypeEList<String>(String.class, this, ReliSRSPackage.PARTICIPANTS__PARTICIPANT);
    }
    return participant;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getRole()
  {
    if (role == null)
    {
      role = new EDataTypeEList<String>(String.class, this, ReliSRSPackage.PARTICIPANTS__ROLE);
    }
    return role;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ReliSRSPackage.PARTICIPANTS__PARTICIPANT:
        return getParticipant();
      case ReliSRSPackage.PARTICIPANTS__ROLE:
        return getRole();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ReliSRSPackage.PARTICIPANTS__PARTICIPANT:
        getParticipant().clear();
        getParticipant().addAll((Collection<? extends String>)newValue);
        return;
      case ReliSRSPackage.PARTICIPANTS__ROLE:
        getRole().clear();
        getRole().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ReliSRSPackage.PARTICIPANTS__PARTICIPANT:
        getParticipant().clear();
        return;
      case ReliSRSPackage.PARTICIPANTS__ROLE:
        getRole().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ReliSRSPackage.PARTICIPANTS__PARTICIPANT:
        return participant != null && !participant.isEmpty();
      case ReliSRSPackage.PARTICIPANTS__ROLE:
        return role != null && !role.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (participant: ");
    result.append(participant);
    result.append(", role: ");
    result.append(role);
    result.append(')');
    return result.toString();
  }

} //ParticipantsImpl
