/*
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import reliS.ui.internal.ReliSActivator;

public class ReliSRSUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ReliSActivator.getInstance().getInjector("org.xtext.slr.ReliSRS");
	}

}
