/*
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReliSRSScopeProvider extends DelegatingScopeProvider {
}
