/**
 * generated by Xtext 2.14.0
 */
package org.xtext.slr;

import org.xtext.slr.AbstractReliSRSRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReliSRSRuntimeModule extends AbstractReliSRSRuntimeModule {
}
