/*
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import reliS.ui.internal.ReliSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReliSRSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ReliSActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ReliSActivator activator = ReliSActivator.getInstance();
		return activator != null ? activator.getInjector(ReliSActivator.ORG_XTEXT_SLR_RELISRS) : null;
	}

}
