/*
 * generated by Xtext 2.14.0
 */
package org.xtext.slr.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.slr.parser.antlr.internal.InternalReliSRSParser;
import org.xtext.slr.services.ReliSRSGrammarAccess;

public class ReliSRSParser extends AbstractAntlrParser {

	@Inject
	private ReliSRSGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReliSRSParser createParser(XtextTokenStream stream) {
		return new InternalReliSRSParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ReliSRSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReliSRSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
